# Copyright (c) 2025 Huawei Technologies Co.,Ltd.
#
# openGauss is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

# Notice:
# 1. (null) explicitly represents empty or null. Meanwhile blank represents undefined.
# 2. GaussMaster encrypts password parameters. Hence, there is no plain-text password after initialization.
# 3. If users use relative path in this file, the current working directory is the directory where this file is located.

[VECTOR]
host =
port =
vector_dbname =
user =
metadatabase =
l2_distance_threshold = 0.9
ssl = true # Using secure protocol by default, users must provide a certificate path.
ssl_certfile = (null) # The certificate file for ssl connections.
ssl_keyfile = (null) # Certificate private key file.
ssl_ca_file = (null)  # CA certificate to validate requests.
ssl_mode = prefer # The ssl mode for ssl connections. Options: disable, prefer, verify-ca.

[DBMIND]
api_prefix = http(s)://***/v1/api/ # base URL ends with /v1/api/
ssl_certfile = (null) # The certificate file for ssl connections.
ssl_keyfile = (null) # Certificate private key file.
ssl_ca_file = (null)  # CA certificate to validate requests.

[WEB-SERVICE]
host =   # Which host to bind for web service. '0.0.0.0' means to bind all.
port =   # Port to listen for web service.
ssl_certfile = (null) # The certificate file for ssl connections.
ssl_keyfile = (null) # Certificate private key file.
ssl_ca_file = (null)  # CA certificate to validate requests.

[LOG]
maxbytes = 10485760 # Default is 10Mb. Maximum size of a single log file. If maxbytes is zero, the file grows indefinitely.
backupcount = 1 # Number of backups of log files.
level = INFO  # Options: DEBUG, INFO, WARNING, ERROR.
log_directory = logs  # Directory to log.

[TIMEZONE]
tz = UTC+8 # only supports UTC, example: UTC-8, UTC+8, UTC-8:35

[SAFETY]
safety_check = false  # Whether to check the question involving unsafe inquiry
