# default llm

model_name: pangu_sigma_unify_plugin_38b

# embedding model
embedding_model:
  enable: True
  model_name: bge-large-finetune
  api_type: bge-large
  api_url: http://*.*.*.*:*/get_embedding_result

# reranker model
reranker_model:
  enable: True
  model_name: bge-reranker-finetune
  api_type: bge-reranker
  api_url: http://*.*.*.*:*/get_reranker_result

# large language model
online_llm:
  pangu_sigma_unify_plugin_38b:
    enable: True
    api_type: Pangu
    api_url: http://*.*.*.*:*/chat/completions
    recommended_config:
      temperature: 0.7
      top_p: 1.0
  pangu_cloud_sigma_unify_plugin_38b:
    enable: False
    api_type: PanguCloud
    api_url: http://*.*.*.*:*/chat/completions
    recommended_config:
      temperature: 0.7
      top_p: 1.0
  Baichuan2-13B-Chat:
    enable: False
    api_type: Baichuan
    api_url: http://*.*.*.*:*/get_qa_baichuan
    recommended_config:
      temperature: 0.7
      top_p: 1.0
  chatglm3-6b:
    enable: False
    api_type: Chatglm
    api_url: http://*.*.*.*:*/get_qa_chatglm
    recommended_config:
      temperature: 0.7
      top_p: 1.0
  Llama3-8B-Chinese-Chat:
    enable: False
    api_type: Llama3
    api_url: http://*.*.*.*:*/get_llm_result_llama3
    recommended_config:
      temperature: 0.7
      top_p: 1.0
